name: action demo workflow
on: push
jobs:
  Example-actions-job:
    name: exploring github actions
    runs-on: ubuntu-latest
    steps:
      # Display the event that triggred the workflow
      - run: echo "the job was triggred by a ${{github.event_name}} event."
      
      # runner info
      - run: echo "the os is ${{runner.os}} hosted by github"

      # repo and branch info
      - run: echo "repo is ${{github.repository}} and branch is ${{github.ref}}"

      # use actions located in github.com/actions
      - name: check out repo code
        uses: actions/checkout@v2

      - run: echo "the repo ${{github.repository}} has been cloned to the runner"
      
      - run: echo "workflow is now ready to test your code on the runner"

      - name: conditional step when event is pull request
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "this event is a pull request"

      - name: list file in the repo
        run: |
          ls ${{github.workspace}}

      - name: setup dotnet runner
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: '7.x'

      - name: display dotnet version
        run: dotnet --version

      - run: echo "the preinstalled tools are located here on the runner ${{runner.tool_cache}}"

      - name: list of files in tool chain
        run: |
          ls ${{ runner.tool_cache }}

      - run: echo "this job status is ${{ job.status }}"
        
         
        
      
      
    
    
  
